<a href="https://colab.research.google.com/github/dipeshMahakali/reinforcement_model/blob/main/nnAndOptimModuleinPytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Create model class
import torch
import torch.nn as nn

#  it is compulsory to inherit our module class with torch.nn's module to get access of all functionality and use it here.
class Model(nn.Module):
  def __init__(self, num_features):
    # then we will invoke constructor of parent class("nn.Module")
    super().__init__()
    # now we will create layer of our neural network, our this model will only have single layer, so will call it linear layer, this willbe our neuron
    self.linear = nn.Linear(num_features, 1)
    # activation function (sigmoid)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):
    out = self.linear(features)
    out = self.sigmoid(out)
    return out



In [2]:
# create dataset
features = torch.rand(10,5)

# create model
model = Model(features.shape[1])

# Call model for forward pass
# model.forward(features)
# logically upper code should done, but pytorch recomendation is to do as bellow
# pytorch developer comunity have use magic class (__call__) that triggers forward() of class when someone called object of class.
model(features)


tensor([[0.4286],
        [0.4441],
        [0.4095],
        [0.4111],
        [0.3657],
        [0.4637],
        [0.4096],
        [0.4081],
        [0.3842],
        [0.4194]], grad_fn=<SigmoidBackward0>)

In [4]:
model.linear.weight
model.linear.bias

Parameter containing:
tensor([-0.3018], requires_grad=True)

In [5]:
# to visualize this whole workflow we will use torchinfo
!pip install torchinfo

In [6]:
from torchinfo import summary

summary(model, input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [7]:
# now we will create neural network with 1 hidden layer
#  it is compulsory to inherit our module class with torch.nn's module to get access of all functionality and use it here.
class Model(nn.Module):
  def __init__(self, num_features):
    # then we will invoke constructor of parent class("nn.Module")
    super().__init__()
    # now we will create layer of our neural network, our this model will only have single layer, so will call it linear layer, this willbe our neuron
    self.linear1 = nn.Linear(num_features, 3)
    # activation function (relu)
    self.relu = nn.ReLU()
    # second layer
    self.linear2 = nn.Linear(3, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):
    out = self.linear1(features)
    out = self.relu(out)
    out = self.linear2(out)
    out = self.sigmoid(out)
    return out


In [8]:
# create dataset
features = torch.rand(10,5)

# create model
model = Model(features.shape[1])

# Call model for forward pass
# model.forward(features)
# logically upper code should done, but pytorch recomendation is to do as bellow
# pytorch developer comunity have use magic class (__call__) that triggers forward() of class when someone called object of class.
model(features)

tensor([[0.3850],
        [0.3621],
        [0.3880],
        [0.3671],
        [0.3806],
        [0.3922],
        [0.3798],
        [0.3909],
        [0.3736],
        [0.3663]], grad_fn=<SigmoidBackward0>)

In [9]:
model.linear1.weight

Parameter containing:
tensor([[ 0.4178,  0.0759, -0.4240,  0.2855,  0.3136],
        [-0.2123, -0.1030, -0.0763,  0.2320, -0.0564],
        [-0.3454,  0.3710, -0.3336,  0.3535,  0.0190]], requires_grad=True)

In [10]:
model.linear2.weight

Parameter containing:
tensor([[ 0.1886,  0.0371, -0.1303]], requires_grad=True)

In [11]:
model.linear1.bias

Parameter containing:
tensor([-0.0708, -0.2672,  0.0585], requires_grad=True)

In [12]:
model.linear2.bias

Parameter containing:
tensor([-0.5443], requires_grad=True)

In [13]:
from torchinfo import summary

summary(model, input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [14]:
# on the way to simplify this neural network we will use Sequential method of nn module
class Model(nn.Module):
  def __init__(self, num_features):
    super().__init__()
    self.network = nn.Sequential(
        nn.Linear(num_features, 3),
        nn.ReLU(),
        nn.Linear(3,1),
        nn.Sigmoid()
    );

  def forward(self, features):
    out = self.network(features)
    return out

# create dataset
features = torch.rand(10,5)

# create model
model = Model(features.shape[1])

# Call model for forward pass
# model.forward(features)
# logically upper code should done, but pytorch recomendation is to do as bellow
# pytorch developer comunity have use magic class (__call__) that triggers forward() of class when someone called object of class.
model(features)

tensor([[0.4384],
        [0.4030],
        [0.4730],
        [0.4316],
        [0.3846],
        [0.4442],
        [0.4807],
        [0.4540],
        [0.4510],
        [0.4271]], grad_fn=<SigmoidBackward0>)